version: "3.8"

services:
  jena-fuseki:
    container_name: f21bd-jena-fuseki
    build:
      context: ./dockerfiles
      dockerfile: jenafuseki.Dockerfile
    ports:
      - 3030:3030
    environment:
      ADMIN_PASSWORD: admin
    volumes:
      - jena-fuseki-data:/fuseki

  neo4j:
    image: neo4j:latest
    container_name: f21bd-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/graphdb
    volumes:
      - neo4j-data:/data

volumes:
  jena-fuseki-data:
  neo4j-data:
